# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CheckIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheckIN(object):
    def setupUi(self, CheckIN):
        CheckIN.setObjectName("CheckIN")
        CheckIN.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(CheckIN)
        self.centralwidget.setObjectName("centralwidget")
        self.bgwidget = QtWidgets.QWidget(self.centralwidget)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255))}")
        self.bgwidget.setObjectName("bgwidget")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 80, 281, 51))
        self.label_2.setStyleSheet("font: 20pt \"Microsoft YaHei UI Light\";;color:rgb(0,0,0);")
        self.label_2.setObjectName("label_2")
        self.Checked_in = QtWidgets.QPushButton(self.bgwidget)
        self.Checked_in.setGeometry(QtCore.QRect(400, 470, 281, 61))
        self.Checked_in.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 170, 127, 255), stop:1 rgba(0, 129, 94, 255));\n"
"border-radius:20px;\n"
"font: 24pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));")
        self.Checked_in.setObjectName("Checked_in")
        self.fnameField = QtWidgets.QLineEdit(self.bgwidget)
        self.fnameField.setGeometry(QtCore.QRect(280, 140, 231, 31))
        self.fnameField.setObjectName("fnameField")
        self.lnameField = QtWidgets.QLineEdit(self.bgwidget)
        self.lnameField.setGeometry(QtCore.QRect(280, 180, 231, 31))
        self.lnameField.setObjectName("lnameField")
        self.idField = QtWidgets.QLineEdit(self.bgwidget)
        self.idField.setGeometry(QtCore.QRect(280, 220, 231, 31))
        self.idField.setObjectName("idField")
        self.genderField = QtWidgets.QLineEdit(self.bgwidget)
        self.genderField.setGeometry(QtCore.QRect(280, 260, 231, 31))
        self.genderField.setObjectName("genderField")
        self.ybField = QtWidgets.QLineEdit(self.bgwidget)
        self.ybField.setGeometry(QtCore.QRect(280, 300, 231, 31))
        self.ybField.setObjectName("ybField")
        self.tvField = QtWidgets.QLineEdit(self.bgwidget)
        self.tvField.setGeometry(QtCore.QRect(280, 340, 231, 31))
        self.tvField.setObjectName("tvField")
        self.dtField = QtWidgets.QLineEdit(self.bgwidget)
        self.dtField.setGeometry(QtCore.QRect(280, 380, 231, 31))
        self.dtField.setObjectName("dtField")
        self.pnField = QtWidgets.QLineEdit(self.bgwidget)
        self.pnField.setGeometry(QtCore.QRect(280, 420, 231, 31))
        self.pnField.setObjectName("pnField")
        self.error_2 = QtWidgets.QLabel(self.bgwidget)
        self.error_2.setGeometry(QtCore.QRect(520, 140, 281, 20))
        self.error_2.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_2.setText("")
        self.error_2.setObjectName("error_2")
        self.error_3 = QtWidgets.QLabel(self.bgwidget)
        self.error_3.setGeometry(QtCore.QRect(520, 180, 281, 20))
        self.error_3.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_3.setText("")
        self.error_3.setObjectName("error_3")
        self.error_4 = QtWidgets.QLabel(self.bgwidget)
        self.error_4.setGeometry(QtCore.QRect(520, 220, 281, 20))
        self.error_4.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_4.setText("")
        self.error_4.setObjectName("error_4")
        self.error_5 = QtWidgets.QLabel(self.bgwidget)
        self.error_5.setGeometry(QtCore.QRect(520, 260, 281, 20))
        self.error_5.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_5.setText("")
        self.error_5.setObjectName("error_5")
        self.error_6 = QtWidgets.QLabel(self.bgwidget)
        self.error_6.setGeometry(QtCore.QRect(520, 300, 281, 20))
        self.error_6.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_6.setText("")
        self.error_6.setObjectName("error_6")
        self.error_7 = QtWidgets.QLabel(self.bgwidget)
        self.error_7.setGeometry(QtCore.QRect(520, 340, 281, 20))
        self.error_7.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_7.setText("")
        self.error_7.setObjectName("error_7")
        self.error_8 = QtWidgets.QLabel(self.bgwidget)
        self.error_8.setGeometry(QtCore.QRect(520, 380, 281, 20))
        self.error_8.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_8.setText("")
        self.error_8.setObjectName("error_8")
        self.error_9 = QtWidgets.QLabel(self.bgwidget)
        self.error_9.setGeometry(QtCore.QRect(520, 420, 281, 20))
        self.error_9.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error_9.setText("")
        self.error_9.setObjectName("error_9")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(250, 10, 291, 61))
        self.label.setStyleSheet("font: 40pt \"Microsoft YaHei UI\";;color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 170, 127, 255), stop:1 rgba(0, 129, 94, 255))\n"
"\n"
"")
        self.label.setObjectName("label")
        self.Go_Back = QtWidgets.QPushButton(self.bgwidget)
        self.Go_Back.setGeometry(QtCore.QRect(90, 470, 281, 61))
        self.Go_Back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(139, 147, 154, 255), stop:1 rgba(91, 100, 103, 255));\n"
"border-radius:20px;\n"
"font: 24pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));")
        self.Go_Back.setObjectName("Go_Back")
        CheckIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CheckIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        CheckIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CheckIN)
        self.statusbar.setObjectName("statusbar")
        CheckIN.setStatusBar(self.statusbar)

        self.retranslateUi(CheckIN)
        QtCore.QMetaObject.connectSlotsByName(CheckIN)

    def retranslateUi(self, CheckIN):
        _translate = QtCore.QCoreApplication.translate
        CheckIN.setWindowTitle(_translate("CheckIN", "MainWindow"))
        self.label_2.setText(_translate("CheckIN", "Please fill all the blanks"))
        self.Checked_in.setText(_translate("CheckIN", "Check in"))
        self.fnameField.setPlaceholderText(_translate("CheckIN", "Enter first name "))
        self.lnameField.setPlaceholderText(_translate("CheckIN", "Enter last name"))
        self.idField.setPlaceholderText(_translate("CheckIN", "Enter ID"))
        self.genderField.setPlaceholderText(_translate("CheckIN", "Enter gender (M or F)"))
        self.ybField.setPlaceholderText(_translate("CheckIN", "Enter Year of birth"))
        self.tvField.setPlaceholderText(_translate("CheckIN", "Vaccine (pfizer , astrazeneca , moderna , j&j)"))
        self.dtField.setPlaceholderText(_translate("CheckIN", "Enter Date&time (DD/MM/YYYY H:M AM/PM)"))
        self.pnField.setPlaceholderText(_translate("CheckIN", "Enter phone number (05XXXXXXXX)"))
        self.label.setText(_translate("CheckIN", "Tawakkalna"))
        self.Go_Back.setText(_translate("CheckIN", "Go Back"))
