# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImmunityCheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImmunityCheck(object):
    def setupUi(self, ImmunityCheck):
        ImmunityCheck.setObjectName("ImmunityCheck")
        ImmunityCheck.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ImmunityCheck)
        self.centralwidget.setObjectName("centralwidget")
        self.bgwidget = QtWidgets.QWidget(self.centralwidget)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255))}")
        self.bgwidget.setObjectName("bgwidget")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 120, 381, 51))
        self.label_2.setStyleSheet("font: 20pt \"Microsoft YaHei UI Light\";;color:rgb(0,0,0);")
        self.label_2.setObjectName("label_2")
        self.Check = QtWidgets.QPushButton(self.bgwidget)
        self.Check.setGeometry(QtCore.QRect(250, 300, 281, 61))
        self.Check.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 170, 127, 255), stop:1 rgba(0, 129, 94, 255));\n"
"border-radius:20px;\n"
"font: 24pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));")
        self.Check.setObjectName("Check")
        self.idField = QtWidgets.QLineEdit(self.bgwidget)
        self.idField.setGeometry(QtCore.QRect(280, 240, 231, 31))
        self.idField.setObjectName("idField")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(250, 50, 291, 61))
        self.label.setStyleSheet("font: 40pt \"Microsoft YaHei UI\";;color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 170, 127, 255), stop:1 rgba(0, 129, 94, 255))\n"
"\n"
"")
        self.label.setObjectName("label")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(520, 240, 271, 31))
        self.error.setStyleSheet("font: 8pt \"Microsoft YaHei UI Light\";\n"
"color: red;")
        self.error.setText("")
        self.error.setObjectName("error")
        self.Go_Back = QtWidgets.QPushButton(self.bgwidget)
        self.Go_Back.setGeometry(QtCore.QRect(250, 370, 281, 61))
        self.Go_Back.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(139, 147, 154, 255), stop:1 rgba(91, 100, 103, 255));\n"
"border-radius:20px;\n"
"font: 24pt \"Microsoft YaHei UI\";\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(223, 223, 223, 255));")
        self.Go_Back.setObjectName("Go_Back")
        self.Color = QtWidgets.QLabel(self.bgwidget)
        self.Color.setEnabled(True)
        self.Color.setGeometry(QtCore.QRect(-4, -8, 821, 591))
        self.Color.setText("")
        self.Color.setObjectName("Color")
        self.Color.raise_()
        self.label_2.raise_()
        self.Check.raise_()
        self.idField.raise_()
        self.label.raise_()
        self.error.raise_()
        self.Go_Back.raise_()
        ImmunityCheck.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ImmunityCheck)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ImmunityCheck.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImmunityCheck)
        self.statusbar.setObjectName("statusbar")
        ImmunityCheck.setStatusBar(self.statusbar)

        self.retranslateUi(ImmunityCheck)
        QtCore.QMetaObject.connectSlotsByName(ImmunityCheck)

    def retranslateUi(self, ImmunityCheck):
        _translate = QtCore.QCoreApplication.translate
        ImmunityCheck.setWindowTitle(_translate("ImmunityCheck", "MainWindow"))
        self.label_2.setText(_translate("ImmunityCheck", "Enter the ID to check immunity"))
        self.Check.setText(_translate("ImmunityCheck", "Check Immunity"))
        self.idField.setPlaceholderText(_translate("ImmunityCheck", "Enter ID"))
        self.label.setText(_translate("ImmunityCheck", "Tawakkalna"))
        self.Go_Back.setText(_translate("ImmunityCheck", "Go Back"))
